brookhong/Surfingkeys

- content_scripts/hints.js
`coordinate` wipes out the holder div, so using `Hints.style()` in custom options had no effect as the style element got erased.
> add styles after clearing holder div

- README.md
- content_scripts/visual.js
this was a bit trickier since the elements aren't in the shadow DOM. The syntax is at least close to the `Hints` styling but I'm definitely open to suggestions there.
> allow styling marks and cursor

- content_scripts/hints.js
https://cl.ly/3M2S3Q1D2w3V/Screen%20Recording%202017-01-15%20at%2002.27%20PM.mov
Allow scrolling while in hints mode. 
Main use case:
1. Press "cf" to open targeted hints mode.
2. Press "j" to scroll down. Notice the hints are regenerated.
3. Press a hint key combination to open in background.
4. Keep scrolling as long as desired. Press "escape" to exit. 
It should support remapped keys. I tested basic remappings, such that if a key was remapped to "j", that could be used as well.
> Rapid open multiple links (cf) while still be able to use j/k to move up down page? #135

- README.md
- README_CN.md
- package.json
With [`npm run`](https://docs.npmjs.com/cli/run-script) any binary can be used without the `node_modules/.bin`
> more convenient build command

- content_scripts/hints.js
I am missing visual feedback of what I've just clicked, a couple of times I pressed the wrong letter and _something_ was clicked, but I've no idea what. 
With this change a pressed link is briefly flashed, just enough to notice what was pressed.
> Briefly flash pressed link

- README.md
- README_CN.md
- content_scripts/content_scripts.js
@brookhong thank you very much for this extension, just found it today and it's an amazing replacement for cVim!!
I use [Colemak keyboard layout](https://colemak.com/), and I hit a limitation because `vmap` is not defined, this PR adds the `vmap` function that follows what `imap` does.
@brookhong I would also love it if you could take a look at my [.surfingkeys.js](https://github.com/kalbasit/dotfiles/blob/master/.surfingkeys.js.erb) and let me know if there's a better way to do it.
> vmap for visual mode.

- content_scripts/hints.js
If any part of a hint is typed as uppercase (i.e. with the shift key held down), open the hint in a new tab.
Fixes #392
My rationale for this change:
This functionality was described by @brookhong in issue #4, in reference to "open[ing] the selected hint in a new tab":
> just hold shift when you press the hint chars, actually you don't need to hold shift from the beginning. Holding shift at the last char is good to go.
This change should behave as described above.
This is also the standard behavior for other Chrome Vim extensions like cVim and Vimium, implying that it's a generally well accepted behavior.
> Holding shift while typing hint opens hint in new tab

- README.md
- content_scripts/runtime.js
- pages/omnibar.js
Previously, when entering text into an OmniBar SearchEngine with a suggestion URL, an HTTP request would be dispatched for each keystroke. When typing long queries, this could lead to rate-limiting, extra network traffic, and is unfriendly to API servers.
---
I've updated the SearchEngine suggestion logic to use a timeout of 200ms
before dispatching an HTTP request. If another keystroke occurs before
this 200ms timeout, the previous request is canceled.
Example Result - When typing "testing" into a SearchEngine dialog with less than 200ms delay between keystrokes:
Old: 7 HTTP requests are dispatched
New: 1 HTTP request is dispatched
Note: It may be desirable to make the timeout duration configurable.
Currently it's hard-coded as 200ms.
---
This has proven to be very beneficial for me. …
> SearchEngine auto-completion suggestions: Prevent extra HTTP requests

- pages/omnibar.js
Added the option to use `%s` as a placeholder within a SearchEngine suggestionURL, which enables the suggestion value to be inserted anywhere within the URL string, rather than just at the very end.
If `%s` is found anywhere within the suggestionURL, the first occurrence of `%s` is replaced with the search term.
If `%s` is **not** found anywhere within the suggestionURL, the search term is appended to the end as prior.
This allows suggestionURLs like the following:
My main use case:
- https://api.datamuse.com/words?md=d&sp=%s*
Other examples:
- https://www.foobar.com/search?q=%s&type=v
- https://www.barqux.com/search/%s.json
- https://www.fizzbuzz.com/keywords/%s/page/1
This should not cause any issues for existing user configurations unless someone is using a suggestionURL which happens …
> Use %s inside suggestionURL as placeholder

- background.js
- manifest.json
This adds the ability to have tab navigation that works on every page, including chrome pages.
You register your desired keys by clicking "Keyboard shortcuts" at the bottom of `chrome://extensions/`.
> Browser-wide tab navigation

- pages/omnibar.js
there are two improvements: 
1. respect config 'runtime.conf.caseSensitive' when comparing user's input against bookmark folder in omnibar
2. keep the last-used bookmark folder keyword so if user want to add bookmarks to the same folder, he doesn't need to input the keyword again, just like the default adding bookmark behavior in Chrome.
Thanks for making this great extension! It is just what I am looking for. I had switched from Vimium after using Vimium for 5+ years.
> respect CaseSensitive settings  and keep last-used bookmark folder keyword in bookmark omnibar

- background.js
`tabs.getSelected` has been deprecated since Chrome 33
(https://developer.chrome.com/extensions/tabs#method-getSelected) and
was never implemented when Firefox moved to WebExtensions
(https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/getSelected).
The recommended way to get the current tab is with `tabs.query` now.
Fixes one of the issues in #621
> Fix pinning/unpinning not working in Firefox

- content_scripts/normal.js
Although there was code to allow `<Tab>` to focus on the next input, it
was always overridden later in the `keydown` event handler by the value
of `settings.enableAutoFocus`.
> Fix #630 <Tab> not cycling between inputs when enableAutoFocus is false

- background.js
Just another small change to add some support for [Firefox Containers](https://support.mozilla.org/en-US/kb/containers), so that links and things opened in new tabs use the origin tab's container. Currently new tabs are always opened without being placed in a container.
Thanks for the great extension and porting it to Firefox also!
> Open new tabs in current Container in Firefox

- content_scripts/utils.js
- content_scripts/visual.js
Since Firefox doesn't implement `scrollIntoViewIfNeeded`,
`isElementPartiallyInViewport` is used which considers elements smaller
than 4x4 pixels not visible. Thus when the cursor in visual mode
contains text smaller than that (e.g. the letter "i"), `scrollIntoView`
will always be called even if the cursor is currently visible.
This adds an optional `ignoreSize` argument to `scrollIntoViewIfNeeded`
to ignore the element size and is only used for the cursor.
Fixes another issue in #621
> Fix unnecessary scrolling when cursor is too small in Firefox

- content_scripts/hints.js
jQuery's `offset` method uses `getBoundingClientRect`
(https://github.com/jquery/jquery/blob/3.2.1/src/offset.js#L99)
which sometimes leads to hints being placed outside the element if it
contains multiple rectangles, such as links that wrap around. Since
hints are always placed at the top, it makes sense to use the topmost
rectangle instead so hints are placed next to element there.
It's most noticeable when `settings.hintAlign` is set to `'left'`, for example (the "ph" hint is for "inline element" at the end):
Using the topmost rectangle instead:
This also fixes `settings.hintAlign = 'right';` placing hints in the
center instead of on the right.
> Use topmost rect instead of bounding rect for hint placement

- background.js
- pages/default.js
Since Firefox `about:` URLs lack two forward slashes, `normalizeURL`
prepends `http://` when trying to open them, resulting in invalid URLs
and errors. This just modifies the regular expression check to not
require slashes so `about:` URLs won't be modified.
This also changes the Firefox new tab to `about:blank` to match
the behavior in Chrome. `about:blank` is used instead of `about:newtab`
because the former allows some commands to be used (e.g. tab
manipulation like switching, closing, and moving) while the latter
doesn't allow any.
> Fix opening about: URLs and change Firefox new tab to about:blank

- content_scripts/hints.js
- pages/front.js
In 45dd0c3 the strings to create the CSS were changed to use template
literals, but the curly braces weren't preserved/became part of the
`${}` placeholders so the CSS was invalid.
Congrats on removing jQuery also!
> Fix custom hint and omnibar styling not working

- background.js
MRU tab sort didn't work for me in Firefox because not all tabs had the data in tabActivated object. This resulted in some comparisons being NaN (e.g. `10 - undefined = NaN`). In firefox this resulted in no-op sort. This PR includes checks to shift tabs without this data to the end.
This results in having a proper sort for tabs with data and tabs without data being at the end, which seems like the most reasonable behavior.
> Fix MRU tab sort in Firefox

- content_scripts/utils.js
In `filterOverlapElements` in content_scripts/utils.js:
- Use the topmost rectangle instead of `getBoundingClientRect` to
account for elements that wrap around
- Additionally check if `el` is inside the element to account for
elements that contain other elements (like bold, span, etc.)
For example, with this page:
<html>
<head></head>
<body>
<a href="#link1">Link1</a>,
<a href="#link2">Link2</a>,
<a href="#bold"><b>Bold link</b></a>,
<a href="#wrapping">Wrapping<br>link</a>
</body>
</html>
And this custom mapping:
mapkey('e', '#1Display a link URL', function() {
Hints.create('a', function(element) {
alert(element.href);
});
});
Hints aren't generated for the last two links currently.
> Edit filter logic to not filter out certain elements for hints

- pages/omnibar.js
Prior changes to SurfingKeys made it difficult or impossible for users
to return results as raw HTML items in custom Search Engine completion
functions.
This change allows for returning an object from the `addSearchAlias()`
`listSuggestion` callback of the following format:
```js
{
html: "<li><b>FooBar</b></li>",  // 'html' is the raw HTML for the item, including a <li> container
props: {                         // 'props' is an object containing any properties to be attached to the DOM element
url: "https://example.com/"
}
}
```
This change makes it possible for me to finally fix https://github.com/b0o/surfingkeys-conf/issues/2
You can see numerous example usages of this functionality in my configuration: https://github.com/b0o/surfingkeys-conf/blob/master/completions.js 
If necessary, I …
> Adapt Omnibar.listResults to accept raw HTML

- pages/default.js
DuckDuckGo mapping was missing from omnibar, ie od. Added support.
> Added DuckDuckGo mapping to omnibar

- content_scripts/hints.js
- create function `createHintsForElements` which takes an array of DOM
elements and creates a hint for each one, optionally filtering out
invisible elements by specifying `attrs.filterInvisible` (default true)
- modify `createHints` function to additionally check for the `cssSelector`
argument to be an Array, and if so choosing to use the
`createHintsForElements` function.
Prior to this change, it was impossible to create hints for sets of elements which cannot be specified through a simple CSS selector, which is not always sufficient. 
See several example usages here: https://github.com/b0o/surfingkeys-conf/blob/3f4a3c1e4df415c222597450dd20d6230d8aac7d/actions.js#L110-L166
> feat(hints): hint creation via array of elements

- pages/omnibar.js
If the user enters a string lacking a URI scheme, try to construct a URL by prepending 'https://', falling back to a query URL for the default search engine.
> tweak: attempt to treat OmniBar input as URL

- LICENSE
Create an additional LICENSE file so that the license information appears in the repository metadata.
https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/
> Add the LICENSE file

- content_scripts/normal.js
When sites set 'scroll-behavior: smooth', previously j/k would trigger
smooth scrolling, even when smooth scrolling was disabled.
Example site:
https://www.travis-ci.org/libkeepass/pykeepass/branches
> Fix scrolling with smooth scrolling disabled with site overrides

- content_scripts/insert.js
- content_scripts/normal.js
enableAutoFocus prevents the page from grabbing focus by blurring any
focus events. However, when we are in insert/passthrough mode, we
ignore intentional blurs by the user and (on some sites) blur the
active element while typing.
This patch changes this behavior so this auto-blurring will not take
place in insert or passthrough mode, as those modes are meant for
user input and/or unimpeded interaction with the page.
The biggest problem site in this case is discord, which sends focus 
events to the focusable element all the time. Surfingkeys used to 
blur the page on these (with enableAutoFocus set to false), but this patch 
resolves that issue.
> Disable autoFocus blurring when in insert or passthrough mode

- README.md
- background.js
Added a "last" value to settings.focusAfterClose to dynamically focus
the previous tab in the stack on close.
> Add setting to switch to last focused tab on stack on tab close

- background.js
As far as I can tell, this check was doing nothing but preventing newly loaded tabs from being added to history (as they hadn't finished loading yet, they were not in the object). Let me know if that's not the case.
Previously, when a new tab was created, the "last/next tab stack" command would not go the last/next tab, but would instead go to the n-2 tab (as it thought the last tab was the current tab). In addition, the "go to last used tab" command seemed to completely break. These two functionalities seem to work with this patch.
> Fix tabHistory not being updated for new tabs

- content_scripts/hints.js
- content_scripts/runtime.js
Addresses #1083  by introducing `settings.hintExplicit` option. Setting this to `true` will prevent the hints module from taking the shortcut where it immediately jumps to the only hint available.
> Added hintExplicit option to disable automatic hint selection

- README.md
- content_scripts/hints.js
- content_scripts/runtime.js
- pages/default.js
- pages/l10n.json
Addresses #417 by adding a setting `hintShiftNonActive` that, when `true`, opens hints in non-active tabs.
Tested on Firefox and Chrome.
> Added setting to open hints in background when holding shift

- content_scripts/normal.js
Insert mode can be entered at the end of this function (line 395), if the cursor
somehow is focused via previous actions, but we are in normal mode. In
this case, we enter insert mode with passFocus=true, which makes the
first focus upon leaving insert mode pass through, even if
enableAutoFocus is set to false.
This fixes that issue by running passFocus = true only when we
actually focus an element.
I am assuming Mode.handleMapKey.call(self, event) does NOT need
passFocus = true, as it is used above without passFocus being set.
Alternatively I can set passFocus=False before the call on 395, but this 
seems cleaner to me. Let me know what you think.
> Fix enableAutoFocus blurring when entering insert mode dynamically

- content_scripts/insert.js
In contenteditable elements where the first child is not a text-node, the end-of-line function would instead go to the start of the line (as it was indexed by 0). This diff changes that so the end-of-line function goes to the end of the children (which, in the cases I'm observing), goes to the end of the entire document.
This isn't the same as the end of line, but it's much better than start of document for me at least. 
The alternative is to recurse inside the contentEditable looking for a text node, instead of just going one level deeper. 
Let me know if you have any questions. I based the change off of this blog post's documentation of selection offsets:
https://javascript.info/selection-range
(this fixes "end of line" in some js chat applications I use)
> Fix EOL in insert mode with contenteditable

- content_scripts/visual.js
On some pages, `document.body` is offset from the viewport. An example is here:
https://minecraft.gamepedia.com/Version_history
On this page, document.body is shifted down 30px, which leads to hints being 30px below where they should be. For `position: absolute`, x/y are relative to the parent and/or `document.body` (as far as I can tell), so we can fix this by subtracting the `document.body` top and left values. Since these values change with scroll (and I just want the offset), I added the scroll values as well. This feels a little hacky, but this is the best solution I came up with.
Let me know if you see a better solution to solve this problem!
Before:
After:
> Fix search marks being offset on some pages

- content_scripts/insert.js
When the browser window looses and gains focus, currently surfingkeys exits insert mode. This is because (for some reason) we get a focus event with `target = window` (even though no focus on the page itself changed). I'm not sure why this event is being fired (or much documentation on the behavior) other than this SO post:
https://stackoverflow.com/questions/3478654/is-there-a-browser-event-for-the-window-getting-focus
To solve this I just ignored focus events with `event.target = window` for the purposes of leaving insert mode. I'm not exactly sure where this handler is attached, but the simplest solution I can see is just ignoring focus events for the window object. 
If you understand this better and see a better solution, let me know. If you want me to put this behavior behind a …
> Prevent browser window focus from exiting insert mode

- content_scripts/visual.js
Unfortunately the change in #1220 wasn't perfect, as it seems like placing `position: relative` or `position: absolute` on `document.body` (or `document.documentElement`) changes the results from boundingClientRect. The previous diff fixed it in the 'absolute/relative' case but not in the other cases. I couldn't find much information on this behavior, other than this comment on this blog post:
https://johnresig.com/blog/getboundingclientrect-is-awesome/#comment-313375
As this is getting rather complicated, I decided to revert the change mostly, and instead place the surfingkeys search hints in `document.documentElement` instead of `document.body` (in the hopes that less people will modify `docuement.documentElement`. However, this method will still not work if people do set `position: …
> Fix search highlights by placing them in document.documentElement

- content_scripts/normal.js
Currently, when an element which is scrollable is deleted or becomes invalid in another way, the element is simply not considered for scrolling anymore, and the next element (from the prior search) is selected. This is fine for webpages which aren't too interactable, but for a webpage which regularly deletes and re-creates it's main scrolling element (some chat applications) this becomes tedious. There is a binding to force recomputing scrollable elements, but it would be a pain to repeatedly press this whenever the page changes. I also tried to add the refresh function to the bindings I use to change the scrolling layout, but they occured too early to make use of the new layout.
This diff changes this case to force a recompute of all scrolling elements when the current scrolling element …
> Recompute scrollable elements automatically when invalidated

- content_scripts/utils.js
Current flow:
Using toggleQuote function mapped as below:
`imapkey("<Ctrl-'>", '#15Toggle quotes in an input element', toggleQuote);`
When the initial string has a quote on the end and if user wants to unquote, **toggleQuote** cant be used.
New flow:
**original string ends with a quote"**   --->  **original string ends with a quote**
> toggleQuote: handle quote only at one end

- docs/API.md
- pages/omnibar.js
Copy url of the currently focussed item in omnibar using
`Ctrl-e` to copy currently focussed item url
Currently we can only copy everything as a json.
> Omnibar: Copy currently focussed url

- content_scripts/clipboard.js
Verified working on Linux in the following browser versions:
- Chrome 89.0.4356.6 dev
- Mozilla Firefox 85.0b4 (Developer Edition)
- Mozilla Firefox 84.0.1
Fixes #1364
> Fix clipboard support in Firefox 84+

- background.js
- pages/options.js
I setting file on GitHub.
1. Surfingkeys don't detect internal error.
2. When network error, and Surfingkeys overwrite setting by default.
I fix that surfingkeys don't nothing when internal error.
> Fix no overwrite when internal error

- src/content_scripts/common/utils.js
- src/content_scripts/common/visual.js
After #1587 I'm able to register inline query but translation is still not working. Pressing `Q` throws `ReferenceError: filterAncestors is not defined` and doesn't show any results. This PR exports and imports the function to fix omnibar translation
> Export filterAncestors for omnibar

- src/content_scripts/common/default.js
URL `chrome://settings/content/cookies` doesn't work.
New URL is `chrome://settings/cookies`.
> Fix URL for "Open Chrome Cookies"

- src/content_scripts/ui/omnibar.js
I added the code to detect ctrl key in onEnter function. It can use ctrl+enter to open all bookmarks under the subdirectory, which is similar to the way of clicking on the directory with the mouse to open all bookmarks.
> Feature: add ctrl+enter to open subdirectory bookmarks

- docs/API.md
- src/content_scripts/common/api.js
- src/content_scripts/front.js
- src/content_scripts/ui/omnibar.js
I really like the new Omnibar search engine icon feature!
One issue I had is that I have numerous search engines configured where the `search_url` does not match the site it's searching.
For example, I use a [Google Custom Search engine](https://developers.google.com/custom-search/) to search the Arch Linux forums, where the `search_url` is `https://cse.google.com/cse/publicurl?cx=xxxxx&q=`. With the old behavior, the Omnibar showed a Google favicon, but I want it to show an Arch Linux favicon. 
With this change, users calling `addSearchAlias` can directly specify the desired favicon via the `favicon_url` property of the new `options` argument. For example:
```javascript
addSearchAlias(
'af', 
'Arch Linux Forums', 
'https://cse.google.com/cse/publicurl?cx=xxxxx&q=', 
's', …
```
> API: Make search engine favicon configurable

- src/background/start.js
- src/content_scripts/ui/omnibar.js
Canvas tainting can be avoided [by adding a `crossOrigin = "Anonymous"` prop to an image element](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image). This makes fetching images a lot more reliable. An added benefit is that secure images can even be loaded from an insecure top-origin, which makes `omnibar.js` lines `1303-1305` unnecessary.
> Fix cross-origin canvas tainting

- docs/API.md
- src/content_scripts/common/api.js
- src/content_scripts/front.js
- src/content_scripts/ui/omnibar.js
A few enhancements to give searchAliases more flexibility:
- The suggestion callback now receives another argument: an object containing the original query and the formatted URL
- Suggestion callbacks can now return promises
> Extend functionality of addSearchAlias suggestions

- src/background/start.js
I'd like to be able to select where I want to save images when using `;di`. After looking through [the chrome downloads docs](https://developer.chrome.com/docs/extensions/reference/downloads/#type-DownloadOptions), it looks like there is a field called `saveAs` for this. I wanted to add this to my personal settings, but it looks like a small change is required to send it to chrome.
With this change, I'm able to achieve it by adding 
```javascript
api.mapkey(";di", "#1Download Image", function() {
api.Hints.create('img', function(element) {
api.RUNTIME('download', {
url: element.src,
saveAs: true,
})
}) 
});
```
to my settings.
As a corollary to this, I wonder why it was chosen not to pass the entire message object, since that way users will be able to use the settings more flexibly.
> Enable file explorer when saving images

- src/content_scripts/ui/frontend.html
This avoids warnings like `This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. > frontend.html`
> Set correct doctype for frontend.html

- src/background/start.js
- src/content_scripts/common/default.js
Two new bindings:
- `gp`: Go to playing tab
- `gxp`: Close playing tab
We can discuss what to do if there are more than one playing tab at a moment.
Solves #1748
> Add playing tab functionality

- src/background/start.js
`gxx` is bound to the 'close all tabs but the current one' action
`gxx` also closes pinned tabs, which in my opinion could be unwanted. Pinned tabs are meant to be more permanent
Tested with `browser=firefox npm run build:dev` on Firefox Nightly
> prevent `gxx` from closing pinned tabs

- docs/API.md
- src/content_scripts/common/api.js
If the `skipMaps` property of `addSearchAlias`'s `options` argument is `true`, key mappings will not be created for the search alias. This is useful in my config because I want to create the mappings myself.
> Add options property skipMaps to addSearchAlias

- src/content_scripts/ui/omnibar.js
If an Omnibar result has a `props.copy` property, it will be copied to the clipboard when the user presses `<Ctrl-c>` on the result item. If both `props.copy` and `props.url` are present, `props.copy` takes precedence.
I'm using this in my config for a Unicode searchAlias that I've made: https://github.com/b0o/surfingkeys-conf/blob/6b6eba4c564953b77d535416f1c0f9752e879a60/src/search-engines.js#L398-L417
> Support custom copy text for Omnibar results

- src/content_scripts/ui/omnibar.js
https://user-images.githubusercontent.com/21299126/201510317-8eb55970-3884-4ba8-8a43-6fe923881f8c.mp4
Previously, when using the arrow keys or tab/shift+tab to select an Omnibar result item, scroll behavior was broken in Firefox and glitchy in Chrome.
In Firefox, if there were more results than could fit in the Omnibar results div, selecting a result item outside of the visible portion of the results div would not cause the result item to be scrolled into view unless the result item was below the bottom of the viewport. This would often cause the selected item to be invisible.
In Chrome, if there were more results than could fit into the Omnibar results div, selecting a result item outside of the visible portion of the results div would sometimes cause the result item to be scrolled just …
> Fix: Ensure selected Omnibar item is scrolled into view

- README.md
It's not obvious from the github interface that there's an active wiki (other than the wiki tab appearing on the repo page), so it would be helpful to specifically mention both the FAQ and wiki in the README.md. I never would have found it if it weren't for someone pointing it out to me in a comment on an issue.
> add link to wiki and FAQ in README.md

- .gitignore
- package.json
- src/content_scripts/common/insert.js
- src/content_scripts/front.js
This PR adds support for editing text within CodeMirror elements. It does so by dispatching a clipboard paste event on the CodeMirror element. The event doesn't interact with the contents of the user's actual clipboard, it's just a synthetic event that transports the text from the vim editor modal to the CodeMirror element.
As an aside, there are two additional areas to look into at some point:
1. ~~After the paste event occurs, the cursor in the CodeMirror element moves from the end of the pasted text back to the beginning of the pasted text. I'm not sure what's provoking the cursor to move to the beginning of the line.~~
2. ~~When editing the contents of a CodeMirror element that contains line numbers (gist editor), those line numbers are brought into the vim editor as if they were …
> CodeMirror vim editor support

- src/background/start.js
resolves https://github.com/brookhong/Surfingkeys/issues/2210
utilize tab's lastAccessed information if available for MRU order
> fix: mru order tab last accessed

- README.md
- README_CN.md
- src/content_scripts/common/insert.js
In Insert mode, Ctrl-f is to move the cursor to the beginning of the line. Can I remove the occupation of Ctrl-f and use Ctrl-a instead? Can this be the same as the shortcut keys in emacs?
https://github.com/brookhong/Surfingkeys/issues/2269
> change Ctrl-f to Ctrl-a

- src/content_scripts/common/hints.js
- src/content_scripts/content.css
Fixes #2294
`div.surfingkeys_hints_host` has the `position: absolute` now
It is stretched over the **entire width of the page** and is located **at the top** of it. The height will be definied via JS
**Hints** are relative to the `div.surfingkeys_hints_host`. Therefore, **overflow** affects them now
The height of the `div.surfingkeys_hints_host` equals to the number of pixels **from the top the page** to the **bottom of the user's view port**
| Before | After |
| - | - |
| ![2025 05 18-01-27-57](https://github.com/user-attachments/assets/6ac01dc2-e001-4f68-89ff-eb75fc8aaa17) | ![2025 05 18-01-28-55](https://github.com/user-attachments/assets/ca43c245-dd68-4432-8b20-e957a776dfce) |
| ![2025 05 18-01-44-09](https://github.com/user-attachments/assets/36b5df2b-f492-4438-869a-027718649cf5) …
> Fix: #2294 Hints overflow the page

- docs/API.md
- src/content_scripts/front.js
- src/content_scripts/ui/frontend.js
- src/user_scripts/index.js
Allow users to define their own custom commands for omnibar.
Useful for less frequent actions where a dedicated keybinding would be overkill.
- Implement a new `addCommand` API.
- Update documentation.
```
api.addCommand("test", "this is a test command", (arg) => {
api.Front.showPopup(arg);
});
```
> feat(commands): Allow users to define custom omnibar commands

- src/content_scripts/ace.js
This import makes ace emacs keybindings work for me.
> add keybinding-emacs of ace-builds
